goBuild:
  stage: build
  image: weavelab/weavebuilder:v1.0.0
  script:
    - /usr/local/bin/npmbuilder
  artifacts:
    paths:
      - dist/
cdTools:
  stage: deploy
  image: weavelab/cd-tools:v1.0.0
  script:
    - /bin/cd-tools
  dependencies:
    - goBuild